kb_categories:
  type: list
  default: ""
  description:
    en: A list of category slugs where the Knowledge Base UI should appear. Defaults to off. 
sort_tags:
  type: enum
  default: alphabetical
  choices:
    - alphabetical
    - popularity 
